---
openapi: 3.0.0
info:
  description: Открытое API для работы с сервисом прогнозирования спроса
  version: 1.0.0
  title: Determination of Tonality
servers:
- url: 'http://ml.determination-of-tonality.local:5000/api/v1'
tags:
- name: PredictTonality
  description: Информация о продажах за определенный период
paths:
  /bagOfWord_method/predict:
    post:
      tags:
      - PredictTonality
      summary: Определение тональности отзывов с помощью метода Bag Of Word | "Мешок слов"
      description: Предсказание тональности отзывов на заранее обученной модели.
      operationId: api.bagOfWord_method.predict
      parameters:
      - name: nameDataSet
        in: query
        description: Название Дата-сета на котором обучалась модель
        schema:
          type: string
      - name: nameClassificator
        in: query
        description: Название классификатора с помощью которого обучалась модель
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/reviews'
      responses:
        '200':
          description: Успешная операция
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/reviews'
        '500':
          description: Операция не удалась
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_500'
  /word2Vec_method/predict:
    post:
      tags:
        - PredictTonality
      summary: Определение тональности отзывов с помощью метода Word2Vec
      description: Предсказание тональности отзывов на заранее обученной модели.
      operationId: api.word2Vec_method.predict
      parameters:
        - name: nameDataSet
          in: query
          description: Название Дата-сета на котором обучалась модель
          schema:
            type: string
        - name: nameClassificator
          in: query
          description: Название классификатора с помощью которого обучалась модель
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/reviews'
      responses:
        '200':
          description: Успешная операция
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/reviews'
        '500':
          description: Операция не удалась
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_500'
components:
  schemas:
    reviews:
      type: object
      properties:
        author:
          type: string
          nullable: true
        pluses:
          type: string
          nullable: true
        minuses:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
        rating:
          type: number
          nullable: true
          format: float
        date:
          type: string
          nullable: true
        review:
          type: string
          nullable: true
        sentiment:
          type: integer
          nullable: true
    inline_response_500:
      properties:
        message:
          type: string
    success_response_200:
      properties:
        message:
          type: string